### PR TITLE
Created test for the function getAllCategories

### PR DESCRIPTION
**Pull request by csaminak**
- Updated dot block for getAllCategories function in the service file.
- Created and wrote asserts to test getAllCategories function.

### CODE REVIEW

**Comment by sm873x** [comment]
@csaminak The tests look good, but in the docblock, I think the correct term for what it returns is Promise (not Object). Check out https://docs.angularjs.org/api/ng/service/$http

**Comment by sm873x** [comment]
Just to clarify, the explanation and definition of a Promise (what you have) is correct. No need to change.

**Comment by csaminak** [comment]
@sm873x  done

**Comment by sm873x** [comment]
@csaminak Done and done.

**Pull request merged**
